apiVersion: v1
kind: Service
metadata:
  name: nginx-alb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # Anotación para ALB
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80