apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-game
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30001  # Puerto específico en el nodo