apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metrics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment  # Nombre del Deployment que se escalará
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_total_per_second  # Métrica personalizada
        target:
          type: AverageValue
          averageValue: 100  # Escalar si hay más de 100 solicitudes por segundo