apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fibonacci-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: fibonacci
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: fibonacci
      minAllowed:
        cpu: "10m"
        memory: "50Mi"
      maxAllowed:
        cpu: "500m"
        memory: "128Mi"
      controlledResources: ["cpu", "memory"]