kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: fibonacci-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests
      target:
        # target 100 milli-requests per second,
        # which is 1 request every two seconds
        type: AverageValue
        averageValue: 500m
  # Tambien podemos añadir el autoescalado HPA por cpu para que se cumpla una u otra
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80