apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-payment
spec:
  selector:
    matchLabels:
      app: app-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: app-payment
    spec:
      containers:
        - name: app-payment
          image: testsysadmin8/mysql-noapp-payment:latest
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-payment-service
  labels:
    app: app-payment
spec:
  selector:
      app: app-payment
  ports:
    - name: payment
      protocol: TCP
      port: 80
      targetPort: 5000