config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        tls Off
        Health_Check Off

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Log_Trim On
        Labels Off
        Annotations Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes_

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_container_name fluent-bit

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Type  _doc
        Host quickstart-es-http
        Port 9200
        HTTP_User elastic
        HTTP_Passwd $PASSWORD
        Replace_Dots On
        tls On
        tls.verify Off
        tls.verify_hostname Off
        Logstash_Format On
        Logstash_Prefix logstash_devops
        Retry_Limit False
        Suppress_Type_Name On
        #network
        net.dns.mode                TCP
        net.keepalive               on
        net.keepalive_idle_timeout  10