pipeline {
  agent any
  environment {
    APP_NAME = "fibonacci"
    DOCKER_USER = "testsysadmin8"
    DOCKER_PASS = 'dockerhub'
    IMAGE_NAME ="${DOCKER_USER}" + "/" + "${APP_NAME}"
    RELEASE = "1.0.0"
    IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
    SERVER = "${SERVER}"
  }
  stages {
    stage('cleanup') {
      steps {
        sh 'docker system prune -a --volumes --force'
      }
    }
    stage("Build & Push Docker Image") {
        steps {
            script {
                docker.withRegistry('',DOCKER_PASS) {
                    docker_image = docker.build "${IMAGE_NAME}"
                }

                docker.withRegistry('',DOCKER_PASS) {
                    docker_image.push("${IMAGE_TAG}")
                    docker_image.push('latest')
                }
            }
        }
    }
    stage ('Cleanup Artifacts') {
           steps {
               script {
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker rmi ${IMAGE_NAME}:latest"
                }
            }
    }
  }
}