apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 5Gi  # Capacidad del volumen
  accessModes:
    - ReadWriteOnce  # Modo de acceso
  hostPath:
    path: /data/pv1  # Ruta en el nodo donde se almacena el volumen