apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acceso solicitado
  resources:
    requests:
      storage: 5Gi  # Capacidad solicitada